import React from "react";
import Gallery from "../../components/Gallery";
import Navigation from "../../components/Navigation";
import Footer from "../../components/Footer";
import { Container } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';


export default function _2021() {

    const images = [
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0010.JPG' }, 
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0011.JPG' }, 
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0012.JPG' }, 
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0013.JPG' }, 
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0014.JPG' }, 
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0015.JPG' }, 
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0016.JPG' }, 
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0017.JPG' }, 
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0018.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0019.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0020.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0021.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0022.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0023.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0024.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0025.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0026.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0027.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0028.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0029.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0030.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0031.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0033.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0034.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0035.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0036.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0037.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0038.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0039.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0040.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0041.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0042.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0043.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0044.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0046.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0047.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0048.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0049.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0050.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0051.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0052.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0053.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0054.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0238.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0239.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0240.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0241.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0242.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0243.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0246.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0247.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0248.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0249.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0250.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0252.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0254.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0256.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0257.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0259.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0260.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0263.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0264.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0265.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0266.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0267.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0268.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0269.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0270.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0271.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0272.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0273.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0274.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0275.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0276.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0277.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0278.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0279.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0280.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0281.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0282.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0283.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0284.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0285.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0286.JPG' }, 
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0287.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0288.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0289.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0290.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0291.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0292.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0293.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0294.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0295.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0296.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0297.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0298.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0300.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0301.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0302.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0303.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0304.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0305.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0306.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0307.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0308.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0309.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0310.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0311.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0312.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0313.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0314.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0315.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0316.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0317.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0318.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0319.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0320.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0321.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0322.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0323.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0324.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0325.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0326.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0327.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0328.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0329.JPG' },
        { original: 'https://s3.amazonaws.com/aaany-assets/images/2021/IMG_0330.JPG' },
        ]

    return (
        <Container>
            <Navigation />
            <div style = {{textAlign: "center"}}>
                <Gallery images = {images} title = "Sir Syed Day Mushaira 2022" year = "2022"></Gallery>
            </div>
            <Footer />
        </Container>
    )
}